apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coinflip-recursive-
spec:
  entrypoint: coinflip
  templates:
    - name: coinflip
      steps:
        # flip a coin
        - - name: flip-coin
            template: flip-coin
          - name: flip-coin-other
            template: flip-coin
        # evaluate the result in parallel
        - - name: heads
            template: heads # call heads template if "heads"
            when: "{{steps.flip-coin.outputs.result}} == heads"
          - name: tails # keep flipping coins if "tails"
            template: coinflip
            when: "{{steps.flip-coin.outputs.result}} == tails"

    - name: flip-coin
      script:
        resources: # limit the resources
          limits:
            memory: 320Mi
            cpu: 1000m
        image: python:alpine3.6
        command: [python]
        source: |
          print("tails")

    - name: heads
      container:
        resources: # limit the resources
          limits:
            memory: 320Mi
            cpu: 1000m
        image: alpine:3.6
        command: [sh, -c]
        args: ['echo "it was heads"']
